### ISSUE TITLE
MILLISECS value multiplier not calculated correctly

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#89] opened 2019-08-06 21:47 UTC
From the docs on leaderboards (https://github.com/RetroAchievements/docs/wiki/Leaderboards) it seems that only one multiplier can be applied to a value.

However, when I compile code like this...

```
function timer_as_millis() => (word(0xABCDEF) / (2 * 60)) * 100
rich_presence_value("Time", timer_as_millis(), "MILLISECS")
```

...RATools generates: `@Time(0x 0b3a95*0.00833333333333333*100)`. The second multiplier is the silently ignored by the engine.

I've tried a bunch of ways of writing `timer_as_millis` to try tricking RATools to generate a single multiplier constant, but had no success. Examples:

```
// fails because / is integer division, function is optimized to integer 0
function timer_as_millis() => word(0xABCDEF) * (100 / (2 * 60))

// the floating point number is parsed as the integer 0
function timer_as_millis() => word(0xABCDEF) * 0.00833333333333333

// removing the function call causes exceptions in the editor
rich_presence_value("Time", word(0xABCDEF) * 0.00833333333333333, "MILLISECS")
```

**Comment by Jamiras** [comment] 2019-08-07 01:37
The first way is the only supported way to write the expression. The parser doesn't currently have any interpretation for non-integer numbers. The inversion for division occurs directly when serializing the expression. 

In the second case, integer math will be performed, resulting in a right value of 0 (100/120). The third and fourth cases aren't supported because non-integers aren't supported in general.

The problem is that once the inversion is completed, the remaining multiplication is not merged into the calculation, but instead treated as a separate entity.

**Closed** 2019-08-10 17:48 UTC
