### ISSUE TITLE
Removing an achievement definition creates a duplicate entry in the list

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#29] opened 2019-02-13 17:08 UTC
I'm not sure exactly if this is intended or not, and if so what it is supposed to communicate. I removed a definition for an unofficial entry, and it was replaced by a duplicate with no rules and no ID.

Original greyed-out unofficial entry:
![image](https://user-images.githubusercontent.com/7488362/52729882-107a0280-2f88-11e9-939a-5e6ebd661560.png)

Duplicate greyed-out empty entry:
![image](https://user-images.githubusercontent.com/7488362/52729905-1ff94b80-2f88-11e9-8df4-789f16046c26.png)

The duplicate also remains in the list after deletion:
![image](https://user-images.githubusercontent.com/7488362/52730590-c134d180-2f89-11e9-8a0f-04b10f8fceaf.png)

**Comment by Jamiras** [comment] 2019-03-08 00:19
I couldn't reproduce with your steps (I'm not even sure I understand them), but I think I was able to reproduce with these steps:

1) Generate a new script for a game with at least one achievement in core or unofficial. 
2) Generate the code for that achievement.
3) "Update Local" for that achievement
4) Modify the title and description in the code that generates the achievement.

This results in a "duplicate" of the achievement as the existing achievement is merged into the generated achievement without updating the editor's achievement ID (this is the bug). Then, when the local achievement attempts to be merged, it can't match the ID and the title and description have been modified so it assumes it's a completely different achievement and creates the duplicate.

Your screenshots don't seem to support this, as all three images appear to have the same title and description, but I'm going to fix this scenario and hope it applies to yours as well. If you can, please clarify your steps to reproduce.

**Comment by rzumer** [comment] 2019-04-03 23:59
The issue (at least the part that is not yet fixed) seems to be related to having an entry with the same title in both Core/Unofficial and Local.

When the definition is in the script, all three entries (remote, local, and script-local) are merged into one.
![image](https://user-images.githubusercontent.com/7488362/55520437-511e0000-564a-11e9-96fa-d41938d492a2.png)

When the definition is removed, and the entry still exists in both Core/Unofficial and Local, an extra entry is created. So there is one greyed-out entry corresponding to the remote definition and another corresponding to the script-local definition, that has no conditions displayed (despite the Local definition not being empty).

![image](https://user-images.githubusercontent.com/7488362/55520589-0781e500-564b-11e9-824d-7d225fba9fc1.png)

This should allow you to reproduce it:

1. Load a title with remote achievements to refresh the core/unofficial sets
2. Create a new script for this title and import all definitions
3. Update Local and add the full set
4. Return to the script and delete a definition now present in both remote and local sets

**Comment by Jamiras** [comment] 2022-11-13 22:08
I cannot reproduce this on the latest master. A singular greyed-out entry appears for the deleted item, and it shows as "Core (Not Generated)" and does show the conditions as expected.

**Closed by Jamiras** 2022-11-13 22:08 UTC
