### ISSUE TITLE
"Parse error -6" in the GUI toolset after generating some large condition sets

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#112] opened 2019-11-29 17:29 UTC
The following code generates a condition set that results in a "Parse error -6" error message when attempting to update the local set in the GUI.

The function counts a specific byte for each entry in a contiguous array of 202 10-byte entries.

```
FLAGS_START = 0x1DB816
FLAGS_BYTES = 10

function count_loop(n) {
    count = 0
    prev_count = 0
    for r in range(0, 201) {
        count = count + byte(FLAGS_START + FLAGS_BYTES * r + 4)
        prev_count = prev_count + prev(byte(FLAGS_START + FLAGS_BYTES * r + 4))
    }

    return count >= n && prev_count == count - 1
}

achievement
(
    title = "Do 1",
    description = "Test",
    points = 1,
    trigger = count_loop(1)
)
```

Removing `&& prev_count == count - 1` solves the issue.

**Comment by Jamiras** [comment] 2020-01-12 21:46
I can reproduce this in 1.6.2. I cannot reproduce in 1.6.3 or master. I suspect it's a duplicate of #96.

**Closed by Jamiras** 2020-01-12 21:46 UTC
