### ISSUE TITLE
[Feature request] Multi-line comments

### ISSUE THREAD

**Issue by PopovMark** [Jamiras/RATools#475] opened 2024-04-20 00:24 UTC
Add multi-line comments, C++ style, like

/*
comment here
*/

This would help if I have to comment out like a big function or several achievements all at once if I don't want to include them or if they're broken. Would be really nice if you didn't have to do like 50+ lines manually.

**Comment by Jamiras** [comment] 2024-04-20 00:48
Duplicate of #79. Already scheduled for the next release.

**Closed by Jamiras** 2024-04-20 00:48 UTC
