### ISSUE TITLE
[Feature Request/Optimization] Combine not equality of mem and delta/prior of adjacent memory into largest size possible

### ISSUE THREAD

**Issue by Souzooka** [Jamiras/RATools#540] opened 2024-10-03 20:09 UTC
Use case/example:
I have a large array of bitflags, and want to check that the sum of the bitcount of all bytes in that array is over a certain value. As a delta check, I want to check that any of that memory has changed since the last update.

```fs
brange = range(0x1000, 0x1100)
count = 200
achievement(
    title="test",
    description="test",
    points=0,
    trigger=sum_of(brange, bitcount) > count &&
            __ornext(any_of(brange, v => byte(v) != prev(byte(v))))
)
```

This will generate a large chain of `Or Next byte(0x1000) != byte(0x1000)`, and so on, up until 0x1100. However, we can do a bit better with a bit of messy coding:

```fs
brange = [0x1000, 0x1100]
count = 200
achievement(
    title="test",
    description="test",
    points=0,
    trigger=sum_of(brange, bitcount) > count &&
            __ornext(any_of(range(brange[0], brange[1], 4), v => dword(v) != prev(dword(v))))
)
```

This now creates an OrNext chain that checks 4 bytes at a time, which makes sense since if any of the 8-bit values at 0x1000, 0x1001, or 0x1002, or 0x1003 are not equal to their value on the last update then the 32-bit value at 0x1000 will also not be equal to its value on the last update.

I request that the RAScript compiler detect and optimize for this case, without the programmer having to explicitly define that they are checking inequality of 32-bit values.

**Comment by Jamiras** [comment] 2024-10-06 21:10
Duplicate of #133.

> The optimizer explicitly does not merge adjacent bytes under the assumption that they could have separate notes, and combining the bytes would make future debugging harder.

> It might be reasonable to combine bytes if they don't have separate code notes, or if the range is annotated with with a length (i.e. "[60 bytes] skill flags")

**Closed** 2024-10-06 21:26 UTC
